export const JAVA_CATEGORIES = {
  PLUGIN: [
    "admin tools",
    "anti-griefing tools",
    "chat related",
    "developer tools",
    "economy",
    "fixes",
    "fun",
    "information",
    "mechanics",
    "miscellaneous",
    "roleplay",
    "teleport",
    "website administration",
    "world generator",
  ],

  WORLD: [
    "adventure",
    "creation",
    "mini game",
    "parkour",
    "puzzle",
    "survival",
    "roleplay",
    "modded world",
  ],

  RESOURCE_PACK: [
    "x512",
    "x256",
    "x128",
    "x64",
    "x32",
    "x16",
    "x8",
    "animated",
    "font pack",
    "medieval",
    "miscellaneous",
    "mod support",
    "modern",
    "traditional",
  ],

  DATA_PACK: [
    "adventure",
    "fantasy",
    "library",
    "magic",
    "miscellaneous",
    "mod support",
    "tech",
    "utility",
  ],

  ADDON: [
    "resource pack",
    "scenarios",
    "world",
  ],

  MOD: [
    "addon",
    "adventure rpg",
    "api",
    "armor",
    "tools",
    "weapons",
    "bug fixes",
    "cosmetic",
    "creative mode",
    "education",
    "food",
    "horror",
    "magic",
    "map",
    "mcreator",
    "miscellaneous",
    "performance",
    "redstone",
    "server utility",
    "storage",
    "technology",
    "world gen",
  ],

  MODPACK: [
    "adventure rpg",
    "combat",
    "expert",
    "exploration",
    "extra large",
    "hardcore",
    "horror",
    "magic",
    "map based",
    "mini game",
    "multiplayer",
    "skyblock",
    "tech",
    "vanilla+",
  ],

  SHADER: [
    "fantasy",
    "realistic",
    "vanilla",
  ],
};

export const BEDROCK_CATEGORIES = {
  ADDON: [
    "weapons",
    "armor",
    "tools",
    "cosmetics",
    "horror",
    "fantasy",
    "food",
    "magic",
    "creation addon",
    "creations",
    "multiplayer",
    "roleplay",
    "performance",
    "skins",
    "survival",
    "technology",
    "utility",
    "vanilla+",
  ],

  MAP: [
    "adventure",
    "creation",
    "custom terrain",
    "minigame",
    "parkour",
    "puzzle",
    "pvp",
    "redstone",
    "survival",
    "roleplay",
  ],

  TEXTURE: [
    "gui",
    "miscellaneous",
    "pvp",
    "realistic",
    "shader",
    "simplistic",
    "themed",
    "x128",
    "x64",
    "x32",
    "x16",
  ],

  SCRIPT: [],
};